### ISSUE TITLE
'working-directory' and 'nuget-package' input parameters cannot be specified at the same time.

### ISSUE THREAD

**Issue by tuyen-vuduc** [edumserrano/nuget-push#2]
I copied your snippet, but I failed.

Can you help check?

Should we use `[string]::IsNullOrEmpty(...)` ([reference](https://stackoverflow.com/questions/13738634/how-can-i-check-if-a-string-is-null-or-empty-in-powershell))

```
- name: Publish NuGet and symbols
   id: nuget-push
   uses: edumserrano/nuget-push@v1.1.0
   with:
      api-key: '${{ secrets.NUGET_PUSH_API_KEY }}' # this example is using GitHub secrets to pass the API key
      working-directory: 'nugets'
    # The next step is using powershell to parse the action's output but you can use whatever you prefer.
    # Note that in order to read the step outputs the action step must have an id.
- name: Log output
```

**Comment by edumserrano** [comment]
Some positive feedback to your query @tuyen-vuduc:
- if you were in my place and were reading a request for help and all that you are given is what you gave me do you think there's enough info to be able to provide assistance? You don't specify what is the error message you're getting or anything else that could help troubleshoot, there can be a thousand problems.

I'm using this action in another project. Like this: https://github.com/edumserrano/dotnet-sdk-extensions/blob/efffac0481a826ea29a3a85f5deaa8b1344f7140/.github/workflows/nuget-publish.yml#L207.

If you give me more info on what error you are getting perhaps I'll be able to assist. Also if the repo where you want to use this is public you can drop me a link and I can take a look at the code as well.

**Comment by tuyen-vuduc** [comment]
@edumserrano Hi, 

Thanks for the reference and sorry for not that very clear.

Have you taken a look at your code again? 

What I did is simply copying your code and put into my workflow and it failed to work.

You can check it [here](https://github.com/NAXAM/braintree-ios-binding/blob/main/.github/workflows/publish-nuget.yml). It's currently commented out.

**Comment by edumserrano** [comment]
I'm not sure if I'll have time to look at this during this holiday times but I spotted one difference. You are running the action using `runs-on: macos-latest`. Maybe there's something unexpected happening with Powershell when running on mac that is causing the error to happen. Can you try to use `runs-on: ubuntu-latest` instead. 

Change this line on your workflow: https://github.com/NAXAM/braintree-ios-binding/blob/7090b36971847332386c3d5c3277f8427e7abb6a/.github/workflows/publish-nuget.yml#L41

Then let me know if it made any difference.

**Comment by tuyen-vuduc** [comment]
@edumserrano Thank you for the reply. I will take extra look because my repo requires MacOS to run. Your snippet looks very helpful, it's great to make it run well on MacOS.

**Comment by edumserrano** [comment]
You can keep the job that builds your app running in MacOS. The job that publishes the NuGet is a separate one and you can change that one to run on ubuntu.

**Comment by tuyen-vuduc** [comment]
Yeah, that's a good point. I will check it out. Thank you.

**Comment by edumserrano** [comment]
The problem was with this bugged condition: https://github.com/edumserrano/nuget-push/pull/3/files. Hopefully this fixes it for you.

**Comment by tuyen-vuduc** [comment]
I will check it out again.

**Comment by tuyen-vuduc** [comment]
@edumserrano It really fixed the issue. Thank you.
